### ISSUE TITLE
Last version of denite isn't working

### ISSUE THREAD

**Issue by jhkersul** [ctaylo21/jarvis#20]
There's a compatibility problem with the latest version of Denite plugin. 
When try to search content on all files, there's the following error:

```vim
[denite] Traceback (most recent call last):
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 26, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 144, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 187, in _start
[denite]     self._init_denite()
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 660, in _init_denite
[denite]     self._denite.on_init(self._context)
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 35, in on_init
[denite]     self._put('on_init', [context])
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 62, in _put
[denite]     return self._child.main(name, args, queue_id=None)
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 69, in main
[denite]     self.on_init(args[0])
[denite]   File "/home/kersul/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 129, in on_init
[denite]     raise NameError('Source "' + name + '" is not found.')
[denite] NameError: Source "-mode=normal" is not found.
[denite] Please execute :messages command.
```

Apparently "-mode=normal" is not a valid command.

**Comment by ctaylo21** [comment]
Good catch. Breaking changes were made on Denite. You can see a similar issue here: https://github.com/Shougo/denite.nvim/issues/648

Waiting on an answer back from Shougo now on mappings.

**Comment by Shougo** [comment]
> NameError: Source "-mode=normal" is not found.

`mode` option is removed now.
